//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string unit { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> price_id { get; set; }
    
        public virtual product product { get; set; }
        public virtual customer customer { get; set; }
        public virtual price_product price_product { get; set; }
    }
}
