//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cart
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        [Range(-1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int quantity { get; set; }
        [Range(-1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int price { get; set; }
        [Range(-1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int discount { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual product product { get; set; }
        public virtual customer customer { get; set; }
    }
}
