//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.carts = new HashSet<cart>();
            this.customer_debt = new HashSet<customer_debt>();
            this.import_inventory = new HashSet<import_inventory>();
            this.inventory_order = new HashSet<inventory_order>();
            this.sales = new HashSet<sale>();
        }
        public int id { get; set; }
        public string created_by { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ và tên !")]
        [StringLength(255, ErrorMessage = "Họ và tên tối đa 255 ký tự.")]
        public string name { get; set; }

        [StringLength(255, ErrorMessage = "Email tối đa 255 ký tự")]
        public string email { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại !")]
        [Display(Name = "Phone Number")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Số điện thoạn không hợp lệ")]
        public string phone { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ !")]
        [StringLength(255, ErrorMessage = "Địa chỉ không quá 255 ký tự.")]
        public string address { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn nhóm khách hàng!")]
        public int type { get; set; }
        public int status { get; set; }

        [StringLength(20, ErrorMessage = "Số tài khoản không quá 20 kí tự")]
        public string account_number { get; set; }

        [StringLength(255, ErrorMessage = "Tên ngân hàng phải dưới 255 ký tự.")]
        public string bank { get; set; }

        public string note { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public int price_level { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string code { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_debt> customer_debt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<import_inventory> import_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_order> inventory_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
    }
}
