//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class inventory_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inventory_order()
        {
            this.customer_debt = new HashSet<customer_debt>();
            this.debts = new HashSet<debt>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        [Required(ErrorMessage = "Vui lòng chọn nhà cung cấp")]
        public Nullable<int> supplier_id { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string create_by { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<decimal> Total { get; set; }
        [Range(0, int.MaxValue, ErrorMessage = "Số tiền trả trước phải lớn hơn {1}")]
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> debt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_debt> customer_debt { get; set; }
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debt> debts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<import_inventory> import_inventory { get; set; }
        public virtual user user { get; set; }
    }
}
