//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.carts = new HashSet<cart>();
            this.import_inventory = new HashSet<import_inventory>();
            this.sale_details = new HashSet<sale_details>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Product code cannot be empty !")]
        [StringLength(100, ErrorMessage = "Code length must be between 1 and 100.", MinimumLength = 1)]
        public string code { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm !")]
        [StringLength(255, ErrorMessage = "Name length must be between 1 and 255.", MinimumLength = 1)]
        public string name { get; set; }
        [Required(ErrorMessage = "Group_id cannot be empty !")]
        public int group_id { get; set; }
        [Required(ErrorMessage = "Category_id cannot be empty !")]
        public int category_id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên đơn vị tính !")]
        [StringLength(100, ErrorMessage = "Unit length must be between 1 and 100.", MinimumLength = 1)]
        public string unit { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int purchase_price { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int sell_price { get; set; }

        [Range(0, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int quantity { get; set; }
        public int status { get; set; }
        public string note { get; set; }
        public int created_by { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên sản phẩm !")]

        [StringLength(100, ErrorMessage = "Product length must be between 1 and 255.", MinimumLength = 1)]
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> deleted_at { get; set; }
        public string name_group { get; set; }
        public string name_category { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart> carts { get; set; }
        public virtual category category { get; set; }
        public virtual group group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<import_inventory> import_inventory { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_details> sale_details { get; set; }
    }
}
