//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class return_supplier
    {
        public int id { get; set; }
        public int inventory_id { get; set; }
        public int quantity { get; set; }
        public string note { get; set; }
        public decimal cost_difference { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual import_inventory import_inventory { get; set; }
    }
}
