//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAP_TEAM05_2022.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.categories = new HashSet<category>();
            this.customer_debt = new HashSet<customer_debt>();
            this.debts = new HashSet<debt>();
            this.groups = new HashSet<group>();
            this.import_inventory = new HashSet<import_inventory>();
            this.inventory_order = new HashSet<inventory_order>();
            this.products = new HashSet<product>();
            this.sales = new HashSet<sale>();
        }

        public string id { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập họ và tên !")]
        [StringLength(255, ErrorMessage = "Nhập họ và tên phải dưới 255 ký tự.")]
        public string name { get; set; }
        [StringLength(255, ErrorMessage = "Nhập Email phải dưới 255 ký tự")]
        public string email { get; set; }
        public string avatar { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập số điện thoại !")]
        [StringLength(11, ErrorMessage = "Sai định dạng số điện thoại", MinimumLength = 11)]

        public string phone { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập địa chỉ !")]
        [StringLength(255, ErrorMessage = "Nhập địa chỉ phải dưới 255 ký tự.")]
        public string address { get; set; }
        public string remember_token { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string asp_id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<category> categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_debt> customer_debt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<debt> debts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group> groups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<import_inventory> import_inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventory_order> inventory_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale> sales { get; set; }
    }
}
